title: Which WIKI is for me?
author: BFG
email: bfgrecording@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Exploring Github, Docker, MediaWiki, DocuWiki, Wiki.js and other options for creating a viable wiki for my school that is scalable to the general public.
# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  bfgrecordingongit # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
